language: node_js
node_js:
- '11'
before_install:
- openssl aes-256-cbc -K $encrypted_5ae270236c4d_key -iv $encrypted_5ae270236c4d_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
script:
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    - npm install
    - npm test
    - npm run build
    - docker build . -t $DOCKER_IMG_NAME:$COMMIT_SHORT

    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git
    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com
    git add preprod/$APP_NAME/naiserator.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"
    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master
    cd ..
    fi
env:
  global:
  - APP_NAME=speil
  - DOCKER_IMG_NAME=navikt/speil
  - GITHUB_APP_ID=19726
  - secure: c+yO35iynf6tkMU2kJPdF8Ejl6GluqtsedhSmElPsbzPH0AnlYL/AkY4+AxJLnf9hqTWesyOwzKtgBd1Fop1vdaNCo5UFOEmj8MlLr6zdY8z6qb/WXCDxTjzvpTWhm5G0OgGiubVxGBtG/VPP+QdkajajwMjC/GpzhRRlAAS/o/REVd6LOTuPXB3G8b6Fgc/7fNrRcjs+oB5qOgbhvKXZwocH5KYvCkvb1YdmWBnxcc6EdoEzyLFbMTss5k1fW93LRvupZIxCfmrrPYA7ETOVJ4k83B1eJbS3C/QnxYqsF+NeIcV7P9Ay+ewDDGmT9VguZjMM3Kih+mCQ0LWbDoSc47N6KwrEz6864jShYGcVjBzrVY+3o3JoaFUG7TcfM3msiLy/RJul0Db3+pBv+9CLadfSWVqf+ux/Cqj3GuhKPD7KxIBqJLRupMPy00dGWTFg1zSHxNCrp7NEsDJSm1RYv6oWOiBLTdoTREWEvA52qq9F5313hN1ngvMVh1jBjbbAQhD54u1xBORYdzdDNcBpfPsyqqnbO24M6XU2NeLx5NHBEsRA4ssuMEXEwfGDEl01VSO7hVfP9LWe/+26WocOcUA5JZh+tR6KlucgQ6bz62hzXqEPrJ7h8Mj4Qahkrydeselhu8TTTHUUkF0ztkBjnKa9/kDZoXeAui0yXgwWyw=
  - secure: VOS0h2H3W43TNq4NKQYIbBm8iZ+kpvye4+CbwqcTw0uIG1gn5iI09s4gMLHF2f4hsgPMvyavQAiaF9Szyb2AXwSuW3RKPrA/LohfFznGULO1mlfboYvelVzcx8AZyuYu47YZAWSfOEwNQPpc0ndfjSuY2ZZUDztCrNk1Dy2ttaXs5yPuk6iUfwxChezr/m7rzKZN1HsH7ZAjT5waB1T0LO/xq1VTklRWT1uZQH5edM/S54vqPRtEaEm17CTzzfKqBVQBNVzPvEr8AfhCb3/6TTtNj6ZPjCRGfFYSqCS6Wrw5tQMBoWNWmpkQD8Ifd9a+HDFNRmlBndMrmmEMtbSaL1X9T2NlHvrGQN2iq93O39exbSlDAr23uavIkxAtykUTQo0vxA+wY6PMxoQAZNxtCeKkUOC0ESHRmKdKEtPP4hKhHVgPIKLDVAQwqrM7TjE4BV7w715XvvHyXb0KKmB7vYSQpRPURMOa84lgRA2vPQsYCm6iOiiG+G6nYUdGlJQV2pxmkf4JaXCyy3CXJ/im3eiBzaVr1ODacbkg5Q7cxoUFtrLbOCTioJufPDRQuG7udDgdE72wosb4y0W+5U19mq+/yDp8MWDkXx61A8Mjgjoq4+jauWEJk6i2nfrIYK1bUo7rKQDqyKjXoOk3rbH92eZlLxZLY/GmUnjeJwi6jnk=
notifications:
  slack:
    secure: FEcZ5FGBEkvX3PbwrU6+VcamAWnQKLea6i2lRqG4/6vt+D2Jw/JlxsPmne/oZY6K/E7DuhqGiUZGcpSrSdqZ9cbm/XLQgLWwoUmIntpPWzBoWd4TyEpV1Z+X73Q+viYVnPWSJp1JR4RVKmrQF4m6mF2Tvqngfx0UQwRk4P0Y1RH5U4tcIEcL43OClygfGGOUALlrpIY9twE6n/x6xunHE/GnbqNbovgIgvvw55hDEzZiUlLkhvtnWwyFrTEYL9BnaEEDPQR+zKhVMu3IWv4s+fOkI1HBAQj/ZYXQrMr8AbXAUPBoY4vYkNooewWnF+ZGVkwHsFAW8SdS5kVJIWpT2LRvBiVMEcX/yhUKv5uOfWDmlrDejpxJ87W5WRx41u272a3Q/uvs9bb9l9IdtuBdKOPjt6w2X67j5l28VKalgp/EKEOxV5TYHNELv3jeezylluaHzVytpYF36ugJHy50EQl/NS34odh6SCuhyTVUw4OlQ5g5G2kSTFu81eZsQUBQyLSamXYCn81FAhGoje8ypzOumX3l9oJuYGXQALFl9pJGkLxF2o81TVoERiPYEtgobqfrQGBNvcyXqHNKELZaiZYZ0wgHwODFzYOK6IcShRZm1Qbi7OUCATLL/6jY242YXJoiIB0yf7yD9hLadRU/KEwHbuLb5tFT07HUyCi3SHY=
