version: 2
commands:
   early_return_for_pull_requests:
      description: >-
         Prevents steps from running if they are spawned from a pull request
      steps:
         - run:
              name: Early return if this build is from a PR
              command: |
                 if [ -n "$CIRCLE_PULL_REQUEST" ]; then
                    echo "Nothing to do for pull requests, so marking this step successful"
                    circleci step halt
                 fi
jobs:
   build-speil:
      working_directory: ~/speil
      docker:
         - image: circleci/node:12.2.0-stretch
      steps:
         - checkout
         - run:
              name: update-npm
              command: "sudo npm install -g npm@latest"
         - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
         - run:
              name: install-npm-deps
              command: npm install
         - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                 - ./node_modules
         - run:
              name: build client
              command: |
                 set -e
                 npm run build
         - run:
              name: build server
              command: |
                 set -e
                 npm run build-server
         - early_return_for_pull_requests
         - run:
              name: assemble and push docker image
              command: |
                 set -e
                 export DOCKER_IMG_NAME="docker.pkg.github.com/navikt/helse-speil/speil"
                 export COMMIT_SHORT="$(git rev-parse --short HEAD)"
                 echo "export DOCKER_IMG_NAME=$DOCKER_IMG_NAME" >> $BASH_ENV
                 echo "export COMMIT_SHORT=$COMMIT_SHORT" >> $BASH_ENV

                 docker build . -t $DOCKER_IMG_NAME:$COMMIT_SHORT

                 echo $GITHUB_PASSWORD | docker login -u "$GITHUB_USERNAME" --password-stdin https://docker.pkg.github.com
                 docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

   deploy-speil-to-preprod:
      working_directory: ~/speil
      docker:
         - image: circleci/node:12.2.0-stretch
      steps:
         - early_return_for_pull_requests
         - setup_remote_docker:
              docker_layer_caching: true
         - run:
              name: deploy speil to preprod
              command: |
                 set -e
                 docker create -v /nais --name naisyamlpreprod alpine:3.4 /bin/true
                 docker cp deploy/preprod.yaml naisyamlpreprod:/nais
                 NAISERATOR=$(docker run --volumes-from naisyamlpreprod mikefarah/yq yq r /nais/preprod.yaml -j)
                 NAISERATOR=$(echo $NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)
                 DEPLOYMENT=$(cat deploy/deployreq.json | jq '.payload.kubernetes.resources += ['$NAISERATOR']')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.environment = "dev-fss"')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')
                 curl -u "$GITHUB_USERNAME:$GITHUB_PASSWORD" --fail \
                    -X POST \
                    -d "$DEPLOYMENT" \
                    -H "Accept: application/vnd.github.ant-man-preview+json" \
                    https://api.github.com/repos/navikt/helse-speil/deployments

   deploy-speil-to-prod:
      working_directory: ~/speil
      docker:
         - image: circleci/node:12.2.0-stretch
      steps:
         - early_return_for_pull_requests
         - setup_remote_docker:
              docker_layer_caching: true
         - run:
              name: deploy speil to prod
              command: |
                 set -e
                 docker create -v /nais --name naisyamlprod alpine:3.4 /bin/true
                 docker cp deploy/prod.yaml naisyamlprod:/nais
                 NAISERATOR=$(docker run --volumes-from naisyamlprod mikefarah/yq yq r /nais/prod.yaml -j)
                 NAISERATOR=$(echo $NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)
                 DEPLOYMENT=$(cat deploy/deployreq.json | jq '.payload.kubernetes.resources += ['$NAISERATOR']')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.environment = "prod-fss"')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')
                 curl -u "$GITHUB_USERNAME:$GITHUB_PASSWORD" --fail \
                    -X POST \
                    -d "$DEPLOYMENT" \
                    -H "Accept: application/vnd.github.ant-man-preview+json" \
                    https://api.github.com/repos/navikt/helse-speil/deployments

   deploy-redis-to-preprod:
      working_directory: ~/speil
      docker:
         - image: circleci/node:12.2.0-stretch
      steps:
         - early_return_for_pull_requests
         - setup_remote_docker:
              docker_layer_caching: true
         - run:
              name: deploy redis to preprod
              command: |
                 set -e
                 docker create -v /nais --name redispreprod alpine:3.4 /bin/true
                 docker cp deploy/redis.yaml redispreprod:/nais
                 NAISERATOR=$(docker run --volumes-from redispreprod mikefarah/yq yq r /nais/redis.yaml -j)
                 DEPLOYMENT=$(cat deploy/deployreq.json | jq '.payload.kubernetes.resources += ['$NAISERATOR']')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.ref = "speil-redis"')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.environment = "dev-fss"')
                 curl -u "$GITHUB_USERNAME:$GITHUB_PASSWORD" --fail \
                       -X POST \
                       -d "$DEPLOYMENT" \
                       -H "Accept: application/vnd.github.ant-man-preview+json" \
                       https://api.github.com/repos/navikt/helse-speil/deployments

   deploy-redis-to-prod:
      working_directory: ~/speil
      docker:
         - image: circleci/node:12.2.0-stretch
      steps:
         - early_return_for_pull_requests
         - setup_remote_docker:
              docker_layer_caching: true
         - run:
              name: deploy redis to prod
              command: |
                 set -e
                 docker create -v /nais --name redisprod alpine:3.4 /bin/true
                 docker cp deploy/redis.yaml redispreprod:/nais
                 NAISERATOR=$(docker run --volumes-from redisprod mikefarah/yq yq r /nais/redis.yaml -j)
                 DEPLOYMENT=$(cat deploy/deployreq.json | jq '.payload.kubernetes.resources += ['$NAISERATOR']')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.ref = "speil-redis"')
                 DEPLOYMENT=$(echo $DEPLOYMENT | jq '.environment = "prod-fss"')
                 curl -u "$GITHUB_USERNAME:$GITHUB_PASSWORD" --fail \
                       -X POST \
                       -d "$DEPLOYMENT" \
                       -H "Accept: application/vnd.github.ant-man-preview+json" \
                       https://api.github.com/repos/navikt/helse-speil/deployments

workflows:
   version: 2
   build-and-deploy:
      jobs:
         - deploy-redis-to-preprod
         - deploy-redis-to-prod
         - build-speil
         - deploy-speil-to-preprod:
              requires:
                 - build-speil
                 - deploy-redis-to-preprod
              filters:
                 branches:
                    only: master
         - deploy-speil-to-prod:
              requires:
                 - build-speil
                 - deploy-redis-to-prod
              filters:
                 branches:
                    only: master
