version: 2
jobs:
   build:
      working_directory: ~/speil
      docker:
         - image: circleci/node:11.13
      steps:
         - checkout
         - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
         - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
         - run:
              name: install-npm-deps
              command: npm install
         - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                 - ./node_modules
         - run:
              name: setup environment
              command: |
                 export APP_NAME=speil
                 export GITHUB_APP_ID=19726
                 export DOCKER_IMG_NAME=navikt/speil
                 export COMMIT_SHORT=$(git rev-parse --short HEAD)
                 export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
         - run:
              name: apps-support
              command: |
                 git clone https://github.com/navikt/github-apps-support.git
                 export PATH=`pwd`/github-apps-support/bin:$PATH
                 echo $HELSECI_KEY > ./helseci.key
                 export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./helseci.key $GITHUB_APP_ID`)
                 echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
                 rm ./helseci.key
         - run:
              name: build and push new version
              command: |
                 set -e
                 if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ "${CIRCLE_BRANCH}" = "master" ]; then
                   npm install
                   npm run build
                   docker build . -t $DOCKER_IMG_NAME:$COMMIT_SHORT

                   echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
                   docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
                   git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git
                   cd helse-iac
                   ./set-image.sh preprod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
                   git config user.name team-helse[bot]
                   git config user.email team-helse[bot]@users.noreply.github.com
                   git add preprod/$APP_NAME/naiserator.yaml
                   git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"
                   git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master
                   cd ..
                 fi
