apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  groups:
    - name: speil-pods
      rules:
        - alert: {{app}} har ingen aktive pods i dev
          expr: kube_deployment_status_replicas_available{namespace="tbd", deployment="speil"} == 0
          for: 2m
          annotations:
            consequence: {{app}} mangler aktive pods i dev!
            action: Se `kubectl describe pod \{{ $labels.kubernetes_pod_name }}` for events,
              og `kubectl logs \{{ $labels.kubernetes_pod_name }}` for logger
            summary: Ingen får brukt speil i dev
          labels:
            namespace: tbd
            severity: critical
