apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  groups:
  - name: speil-pods
    rules:
    - alert: Aktive pods for \{{ $labels.deployment }}
      expr: kube_deployment_status_replicas_available{namespace="tbd", deployment="speil"} == 0
      for: 2m
      annotations:
        consequence: Hvis speil ikke har noen pods får ikke saksbehandlerne gjort jobben sin
        action: "Bruk `kubectl describe application \{{ $labels.deployment }}` for events
          og `kubectl logs -l app=\{{ $labels.deployment }}` for logger."
        summary: "`\{{ $labels.deployment }}` mangler aktive pods i prod"
      labels:
        namespace: tbd
        severity: critical
