apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{team}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://speil.nais.adeo.no
    - https://speil.intern.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: isAlive
    periodSeconds: 5
    timeout: 1
  readiness:
    initialDelay: 20
    path: isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  prometheus:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
  webproxy: true
  secureLogs:
    enabled: true
  envFrom:
    - secret: speil
    - secret: speil-redis
  env:
    - name: DEBUG
      value: global-tunnel
    - name: REDIS_HOST
      value: speil-redis.tbd.svc.nais.local
    - name: REDIS_PORT
      value: '6379'
    - name: CLIENT_ID_SPESIALIST
      value: api://prod-fss.tbd.spesialist/.default
    - name: LOGOUT_URL
      value: https://speil.nais.adeo.no
