apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: speil
  namespace: default
  labels:
    team: tbd
spec:
  image: navikt/speil:5e89f02
  port: 3000
  team: tbd
  liveness:
    path: isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://speil.nais.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
  secrets: true
  webproxy: true
  env:
    - name: REDIRECT_URL
      value: https://speil.nais.adeo.no/callback
    - name: API_BASE_URL
      value: https://spade.nais.adeo.no
