apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://speil.nais.adeo.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: isAlive
    periodSeconds: 5
    timeout: 1
  readiness:
    initialDelay: 20
    path: isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  prometheus:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/prod/creds/helse-speil
  webproxy: true
  secureLogs:
    enabled: true
  env:
    - name: REDIRECT_URL
      value: https://speil.nais.adeo.no/callback
    - name: API_BASE_URL
      value: https://spesialist.nais.adeo.no
    - name: DEBUG
      value: global-tunnel
    - name: REDIS_HOST
      value: speil-redis.tbd.svc.nais.local
    - name: REDIS_PORT
      value: '6379'
    - name: CLIENT_ID_SPESIALIST
      value: c0430474-9abb-4062-9974-0dfe6a375046
