apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{team}}
  name: {{app}}-redis
  namespace: {{team}}
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  accessPolicy:
    inbound:
      rules:
        - application: speil
          cluster: dev-gcp
          namespace: tbd
  image: bitnami/redis:6.2
  port: 6379
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: speil-redis