apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{team}}
  name: {{app}}-redis
  namespace: {{team}}
spec:
  image: navikt/secure-redis:5.0.3-alpine-2
  port: 6379
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 6379
  envFrom:
    - secret: speil-redis
