name: deploy specific commit to dev

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'SHA of the commit to deploy'
        required: true

env:
  APP: speil
  TEAM: tbd
  IMAGE: ghcr.io/${{ github.repository }}/speil

jobs:
  set_version:
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.event.inputs.commitHash }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      tag: ${{ env.TAG }}

  build:
    runs-on: ubuntu-latest
    needs: set_version
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ needs.set_version.outputs.tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Cache node deps
        id: cache-node
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: set timezone
        run: export TZ=utc
      - name: install root dependencies
        run: npm ci --ignore-scripts
      - name: install package dependencies
        run: npx lerna bootstrap
      - name: build
        run: npm run build
      - name: build docker image
        run: |
          npm prune --production
          docker build . --pull -t ${{ env.IMAGE }}:${{ needs.set_version.outputs.tag }}
      - name: Login to GitHub Pkg Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push docker image
        run: |
          docker push ${{ env.IMAGE }}:${{ needs.set_version.outputs.tag }}

  deployDev:
    name: Deploy to dev
    needs: [set_version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ needs.set_version.outputs.tag }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml,deploy/alerts-dev.yml,deploy/redis-dev.yml
          VAR: "image=${{env.IMAGE}}:${{ needs.set_version.outputs.tag }},team=${{env.TEAM}},app=${{env.APP}}"

