name: master

on:
  push:
    branches:
      - master
env:
  APP: speil
  TEAM: tbd

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: set timezone
        run: export TZ=utc
      - name: install root dependencies
        run: npm ci --ignore-scripts
      - name: install package dependencies
        run: npx lerna bootstrap
      - name: get jest cache directory
        run: |
          jest_command=packages/frontend/node_modules/jest-cli/bin/jest.js # fordi å installere jest med npx tar ti sekunder
          echo "jest_cache_dir=$($jest_command --showConfig | jq -r '.configs[0].cacheDirectory')" >> $GITHUB_ENV
      - name: Cache jest
        id: cache-jest
        uses: actions/cache@v3
        with:
          path: ${{ env.jest_cache_dir }}
          key: ${{ runner.os }}-jest-${{ hashFiles('packages/backend/jest.config.js', 'packages/frontend/jest.config.js') }}
          restore-keys: ${{ runner.os }}-jest-
      - name: test
        run: npm run test-ci
      - name: build
        run: npm run build
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: |
            cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          # full invalidering for å unngå å ta vare på eldre versjoner
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
      - name: install cypress
        run: npx cypress install
      - name: run e2e-test
        run: npm run e2e-test
      - name: Archive Cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: e2e-tests/cypress/videos
      - name: build docker image
        run: |
          npm prune --production
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: Deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml,deploy/alerts-dev.yml,deploy/redis-dev.yml
          VAR: "image=${{ needs.set_version.outputs.tag }},team=${{env.TEAM}},app=${{env.APP}}"

  deployProd:
    name: Deploy to prod
    needs: [deployDev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod.yml,deploy/alerts-prod.yml,deploy/redis-prod.yml
          VAR: "image=${{ needs.set_version.outputs.tag }},team=${{env.TEAM}},app=${{env.APP}}"
