name: prs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: install root dependencies
      run: npm ci --ignore-scripts
    - name: install package dependencies
      run: npx lerna bootstrap
    - name: test
      run: npm run test
    - name: build
      run: npm run build
    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: |
          cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
        # full invalidering for 책 unng책 책 ta vare p책 eldre versjoner
        restore-keys: |
          cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
    - name: install cypress
      run: npx cypress install
    - name: run e2e-test
      run: npm run e2e-test
    - name: Archive Cypress artifacts
      uses: actions/upload-artifact@v3
      with:
        name: videos
        path: e2e-tests/cypress/videos
