name: prs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: install root dependencies
      run: npm ci --ignore-scripts
    - name: install package dependencies
      run: npx lerna bootstrap
    - name: test
      run: npm run test
    - name: build
      run: npm run build
